-- Full Database Schema Dump
-- Generated by Script

-- Table: addresses
CREATE TABLE IF NOT EXISTS public.addresses (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    label character varying(50),
    city character varying(100),
    street character varying(100),
    details text,
    is_default boolean DEFAULT false,
    CONSTRAINT addresses_id_not_null NOT NULL id,
    CONSTRAINT addresses_pkey PRIMARY KEY (id),
    CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_fk_addresses_user ON public.addresses USING btree (user_id);

-- Table: ai_generation_logs
CREATE TABLE IF NOT EXISTS public.ai_generation_logs (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    medicine_id uuid,
    generated_by uuid,
    generated_data jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_generation_logs_id_not_null NOT NULL id,
    CONSTRAINT ai_generation_logs_pkey PRIMARY KEY (id),
    CONSTRAINT ai_generation_logs_medicine_id_fkey FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    CONSTRAINT ai_generation_logs_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES users(id)
);


-- Table: announcements
CREATE TABLE IF NOT EXISTS public.announcements (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255) NOT NULL,
    message text NOT NULL,
    target_audience character varying(50) NOT NULL,
    scheduled_for timestamp without time zone,
    status character varying(20) DEFAULT 'draft'::character varying,
    created_by uuid,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT announcements_id_not_null NOT NULL id,
    CONSTRAINT announcements_message_not_null NOT NULL message,
    CONSTRAINT announcements_pkey PRIMARY KEY (id),
    CONSTRAINT announcements_status_check CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'scheduled'::character varying, 'sent'::character varying])::text[]))),
    CONSTRAINT announcements_target_audience_check CHECK (((target_audience)::text = ANY ((ARRAY['all'::character varying, 'staff'::character varying, 'active_orders'::character varying, 'customers'::character varying, 'doctors'::character varying, 'admins'::character varying])::text[]))),
    CONSTRAINT announcements_target_audience_not_null NOT NULL target_audience,
    CONSTRAINT announcements_title_not_null NOT NULL title
);


-- Table: audit_logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    action text,
    entity character varying(50),
    entity_id uuid,
    timestamp timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_id_not_null NOT NULL id,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
    CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);


-- Table: availability_notifications
CREATE TABLE IF NOT EXISTS public.availability_notifications (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    medicine_id uuid,
    is_sent boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT availability_notifications_id_not_null NOT NULL id,
    CONSTRAINT availability_notifications_medicine_id_fkey FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    CONSTRAINT availability_notifications_pkey PRIMARY KEY (id),
    CONSTRAINT availability_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);


-- Table: chats
CREATE TABLE IF NOT EXISTS public.chats (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    patient_id uuid,
    pharmacist_id uuid,
    status character varying(20) DEFAULT 'active'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_message_at timestamp without time zone,
    CONSTRAINT chats_status_check CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'closed'::character varying])::text[]))),
    CONSTRAINT chats_id_not_null NOT NULL id,
    CONSTRAINT chats_pkey PRIMARY KEY (id),
    CONSTRAINT chats_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES users(id),
    CONSTRAINT chats_pharmacist_id_fkey FOREIGN KEY (pharmacist_id) REFERENCES users(id)
);

CREATE INDEX idx_chats_participants ON public.chats USING btree (patient_id, pharmacist_id);

-- Table: email_verifications
CREATE TABLE IF NOT EXISTS public.email_verifications (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    otp_hash text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    verified boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT email_verifications_expires_at_not_null NOT NULL expires_at,
    CONSTRAINT email_verifications_id_not_null NOT NULL id,
    CONSTRAINT email_verifications_otp_hash_not_null NOT NULL otp_hash,
    CONSTRAINT email_verifications_pkey PRIMARY KEY (id),
    CONSTRAINT email_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT email_verifications_user_id_not_null NOT NULL user_id
);

CREATE INDEX idx_email_verifications_user ON public.email_verifications USING btree (user_id);

-- Table: inventory_adjustments
CREATE TABLE IF NOT EXISTS public.inventory_adjustments (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    medicine_id uuid,
    adjustment_type character varying(50) NOT NULL,
    quantity_change integer NOT NULL,
    reference_id uuid,
    performed_by uuid,
    reason text,
    created_at timestamp without time zone DEFAULT now(),
    shift_id uuid,
    CONSTRAINT chk_adjustment_type_valid CHECK (((adjustment_type)::text = ANY ((ARRAY['initial_stock'::character varying, 'migration_initial_stock'::character varying, 'sale'::character varying, 'return_restock'::character varying, 'return_discard'::character varying, 'manual_adjustment'::character varying, 'restock'::character varying, 'damage'::character varying, 'expired'::character varying, 'correction'::character varying])::text[]))),
    CONSTRAINT inventory_adjustments_adjustment_type_not_null NOT NULL adjustment_type,
    CONSTRAINT inventory_adjustments_id_not_null NOT NULL id,
    CONSTRAINT inventory_adjustments_medicine_id_fkey FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    CONSTRAINT inventory_adjustments_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES users(id),
    CONSTRAINT inventory_adjustments_pkey PRIMARY KEY (id),
    CONSTRAINT inventory_adjustments_quantity_change_not_null NOT NULL quantity_change,
    CONSTRAINT inventory_adjustments_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES shifts(id)
);

CREATE INDEX idx_inventory_adjustments_medicine ON public.inventory_adjustments USING btree (medicine_id);
CREATE INDEX idx_inventory_adjustments_shift ON public.inventory_adjustments USING btree (shift_id);

-- Table: medicines
CREATE TABLE IF NOT EXISTS public.medicines (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(150) NOT NULL,
    description text,
    benefits text,
    side_effects text,
    image_url text,
    reviewed_by uuid,
    reviewed_at timestamp without time zone,
    quantity_deprecated integer DEFAULT 0,
    low_stock_threshold integer DEFAULT 5,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    price numeric DEFAULT 0.00,
    category character varying(50) DEFAULT 'featuredMedicines'::character varying,
    icon character varying(50),
    original_price numeric,
    ai_generated boolean DEFAULT false,
    ai_reviewed boolean DEFAULT false,
    ai_reviewed_at timestamp without time zone,
    CONSTRAINT medicines_id_not_null NOT NULL id,
    CONSTRAINT medicines_name_not_null NOT NULL name,
    CONSTRAINT medicines_pkey PRIMARY KEY (id),
    CONSTRAINT medicines_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

CREATE INDEX idx_medicines_name_search ON public.medicines USING btree (name text_pattern_ops);

-- Table: messages
CREATE TABLE IF NOT EXISTS public.messages (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    chat_id uuid,
    sender_id uuid,
    message text,
    type character varying(10) DEFAULT 'text'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    read boolean DEFAULT false,
    CONSTRAINT messages_type_check CHECK (((type)::text = ANY ((ARRAY['text'::character varying, 'image'::character varying])::text[]))),
    CONSTRAINT messages_id_not_null NOT NULL id,
    CONSTRAINT messages_pkey PRIMARY KEY (id),
    CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,
    CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users(id)
);

CREATE INDEX idx_messages_chat_created ON public.messages USING btree (chat_id, created_at);

-- Table: notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(200),
    message text,
    type character varying(20),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    sender_id uuid,
    scope character varying(20) DEFAULT 'global'::character varying,
    related_id uuid,
    CONSTRAINT notifications_id_not_null NOT NULL id,
    CONSTRAINT notifications_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT notifications_scope_check CHECK (((scope)::text = ANY ((ARRAY['global'::character varying, 'users'::character varying, 'staff'::character varying])::text[]))),
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY (ARRAY['system'::text, 'transactional'::text, 'stock_alert'::text, 'announcement'::text])))
);

CREATE INDEX idx_notifications_sender ON public.notifications USING btree (sender_id);
CREATE INDEX idx_notifications_scope ON public.notifications USING btree (scope);

-- Table: order_items
CREATE TABLE IF NOT EXISTS public.order_items (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid,
    medicine_id uuid,
    quantity integer NOT NULL,
    price numeric NOT NULL,
    CONSTRAINT order_items_id_not_null NOT NULL id,
    CONSTRAINT order_items_quantity_not_null NOT NULL quantity,
    CONSTRAINT order_items_price_not_null NOT NULL price,
    CONSTRAINT order_items_pkey PRIMARY KEY (id),
    CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT order_items_medicine_id_fkey FOREIGN KEY (medicine_id) REFERENCES medicines(id)
);

CREATE INDEX idx_fk_order_items_order ON public.order_items USING btree (order_id);
CREATE INDEX idx_fk_order_items_medicine ON public.order_items USING btree (medicine_id);

-- Table: order_status_logs
CREATE TABLE IF NOT EXISTS public.order_status_logs (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL,
    old_status character varying(50),
    new_status character varying(50) NOT NULL,
    changed_by uuid NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT order_status_logs_changed_at_not_null NOT NULL changed_at,
    CONSTRAINT order_status_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES users(id),
    CONSTRAINT order_status_logs_changed_by_not_null NOT NULL changed_by,
    CONSTRAINT order_status_logs_id_not_null NOT NULL id,
    CONSTRAINT order_status_logs_new_status_not_null NOT NULL new_status,
    CONSTRAINT order_status_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT order_status_logs_order_id_not_null NOT NULL order_id,
    CONSTRAINT order_status_logs_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_order_status_logs_order ON public.order_status_logs USING btree (order_id);
CREATE INDEX idx_order_status_logs_date ON public.order_status_logs USING btree (changed_at DESC);

-- Table: orders
CREATE TABLE IF NOT EXISTS public.orders (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_uid character varying(50) NOT NULL,
    user_id uuid,
    processed_by uuid,
    address_id uuid,
    phone character varying(20),
    order_type character varying(20) DEFAULT 'instant'::character varying,
    scheduled_for timestamp without time zone,
    status character varying(20) DEFAULT 'pending'::character varying,
    total_price numeric,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    subtotal numeric,
    delivery_fee numeric,
    discount_total numeric,
    promotion_id uuid,
    tax_amount numeric DEFAULT 0,
    invoice_url text,
    payment_status character varying(20) DEFAULT 'unpaid'::character varying,
    shift_id uuid,
    phone_number character varying(20),
    completed_shift_id uuid,
    prescription_id uuid,
    completed_at timestamp without time zone,
    canceled_at timestamp without time zone,
    returned_at timestamp without time zone,
    returned_shift_id uuid,
    admin_notes text,
    return_status character varying(20) DEFAULT 'none'::character varying,
    CONSTRAINT orders_order_type_check CHECK (((order_type)::text = ANY ((ARRAY['instant'::character varying, 'scheduled'::character varying])::text[]))),
    CONSTRAINT orders_id_not_null NOT NULL id,
    CONSTRAINT orders_order_uid_not_null NOT NULL order_uid,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_order_uid_key UNIQUE (order_uid),
    CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT orders_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES users(id),
    CONSTRAINT orders_address_id_fkey FOREIGN KEY (address_id) REFERENCES addresses(id),
    CONSTRAINT orders_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES promotions(id),
    CONSTRAINT orders_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES shifts(id),
    CONSTRAINT orders_completed_shift_id_fkey FOREIGN KEY (completed_shift_id) REFERENCES shifts(id),
    CONSTRAINT orders_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES prescriptions(id),
    CONSTRAINT orders_returned_shift_id_fkey FOREIGN KEY (returned_shift_id) REFERENCES shifts(id)
);

CREATE INDEX idx_orders_status ON public.orders USING btree (status);
CREATE INDEX idx_fk_orders_address ON public.orders USING btree (address_id);
CREATE INDEX idx_fk_orders_promotion ON public.orders USING btree (promotion_id);
CREATE INDEX idx_orders_shift ON public.orders USING btree (shift_id);
CREATE INDEX idx_orders_user_created ON public.orders USING btree (user_id, created_at DESC);
CREATE INDEX idx_orders_created_at ON public.orders USING btree (created_at DESC);
CREATE INDEX idx_orders_completed_shift ON public.orders USING btree (completed_shift_id);
CREATE INDEX idx_orders_completed_at ON public.orders USING btree (completed_at);
CREATE INDEX idx_orders_returned_at ON public.orders USING btree (returned_at);
CREATE INDEX idx_orders_returned_shift ON public.orders USING btree (returned_shift_id);
CREATE INDEX idx_orders_uid_trgm ON public.orders USING gin (order_uid gin_trgm_ops);

-- Table: password_resets
CREATE TABLE IF NOT EXISTS public.password_resets (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    otp_hash text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    verified boolean DEFAULT false,
    attempts integer DEFAULT 0,
    reset_token text,
    token_expires_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    resend_count integer DEFAULT 0,
    last_sent_at timestamp without time zone DEFAULT now(),
    CONSTRAINT password_resets_expires_at_not_null NOT NULL expires_at,
    CONSTRAINT password_resets_id_not_null NOT NULL id,
    CONSTRAINT password_resets_otp_hash_not_null NOT NULL otp_hash,
    CONSTRAINT password_resets_pkey PRIMARY KEY (id),
    CONSTRAINT password_resets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT password_resets_user_id_not_null NOT NULL user_id
);

CREATE INDEX idx_password_resets_user ON public.password_resets USING btree (user_id);
CREATE INDEX idx_password_resets_expires ON public.password_resets USING btree (expires_at);

-- Table: payments
CREATE TABLE IF NOT EXISTS public.payments (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid,
    user_id uuid,
    amount numeric NOT NULL,
    payment_method character varying(50) NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    shift_id uuid,
    CONSTRAINT payments_id_not_null NOT NULL id,
    CONSTRAINT payments_amount_not_null NOT NULL amount,
    CONSTRAINT payments_payment_method_not_null NOT NULL payment_method,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT payments_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES shifts(id)
);

CREATE INDEX idx_payments_order ON public.payments USING btree (order_id);
CREATE INDEX idx_payments_shift ON public.payments USING btree (shift_id);
CREATE INDEX idx_payments_created_at ON public.payments USING btree (created_at DESC);

-- Table: pharmacy_settings
CREATE TABLE IF NOT EXISTS public.pharmacy_settings (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tax_rate numeric DEFAULT 0.10,
    delivery_fee numeric DEFAULT 5.00,
    created_at timestamp without time zone DEFAULT now(),
    modified_by uuid,
    is_open boolean DEFAULT true,
    CONSTRAINT pharmacy_settings_id_not_null NOT NULL id,
    CONSTRAINT pharmacy_settings_pkey PRIMARY KEY (id)
);


-- Table: pharmacy_status_logs
CREATE TABLE IF NOT EXISTS public.pharmacy_status_logs (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    is_open boolean DEFAULT true,
    created_by uuid,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT pharmacy_status_logs_id_not_null NOT NULL id,
    CONSTRAINT pharmacy_status_logs_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_pharmacy_logs_created ON public.pharmacy_status_logs USING btree (created_at DESC);

-- Table: prescription_ai_results
CREATE TABLE IF NOT EXISTS public.prescription_ai_results (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    prescription_id uuid,
    raw_text text,
    suggested_meds jsonb,
    confidence_score numeric,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT prescription_ai_results_id_not_null NOT NULL id,
    CONSTRAINT prescription_ai_results_pkey PRIMARY KEY (id),
    CONSTRAINT prescription_ai_results_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE CASCADE,
    CONSTRAINT prescription_ai_results_prescription_id_key UNIQUE (prescription_id)
);

CREATE INDEX idx_fk_ai_results_prescription ON public.prescription_ai_results USING btree (prescription_id);

-- Table: prescription_final
CREATE TABLE IF NOT EXISTS public.prescription_final (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    prescription_id uuid,
    approved_by uuid,
    final_meds jsonb,
    notes text,
    approved_at timestamp without time zone,
    total_price numeric DEFAULT 0,
    CONSTRAINT prescription_final_id_not_null NOT NULL id,
    CONSTRAINT prescription_final_pkey PRIMARY KEY (id),
    CONSTRAINT prescription_final_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE CASCADE,
    CONSTRAINT prescription_final_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE INDEX idx_fk_final_prescription ON public.prescription_final USING btree (prescription_id);

-- Table: prescriptions
CREATE TABLE IF NOT EXISTS public.prescriptions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    image_url text,
    status character varying(20) DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    shift_id uuid,
    CONSTRAINT prescriptions_id_not_null NOT NULL id,
    CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
    CONSTRAINT prescriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT prescriptions_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES shifts(id) ON DELETE SET NULL,
    CONSTRAINT prescriptions_status_check CHECK (((status)::text = ANY ((ARRAY['reviewing'::character varying, 'processing'::character varying, 'outtodelevery'::character varying, 'canceled'::character varying, 'done'::character varying, 'pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'completed'::character varying])::text[])))
);

CREATE INDEX idx_prescriptions_status ON public.prescriptions USING btree (status);
CREATE INDEX idx_fk_prescriptions_user ON public.prescriptions USING btree (user_id);
CREATE INDEX idx_prescriptions_shift ON public.prescriptions USING btree (shift_id);

-- Table: product_requests
CREATE TABLE IF NOT EXISTS public.product_requests (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    product_name character varying(255) NOT NULL,
    description text,
    status character varying(50) DEFAULT 'pending'::character varying,
    matched_medicine_id uuid,
    doctor_notes text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_requests_id_not_null NOT NULL id,
    CONSTRAINT product_requests_matched_medicine_id_fkey FOREIGN KEY (matched_medicine_id) REFERENCES medicines(id),
    CONSTRAINT product_requests_pkey PRIMARY KEY (id),
    CONSTRAINT product_requests_product_name_not_null NOT NULL product_name,
    CONSTRAINT product_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);


-- Table: promotion_usage
CREATE TABLE IF NOT EXISTS public.promotion_usage (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    promotion_id uuid,
    user_id uuid,
    order_id uuid,
    discount_applied numeric,
    used_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT promotion_usage_id_not_null NOT NULL id,
    CONSTRAINT promotion_usage_pkey PRIMARY KEY (id),
    CONSTRAINT promotion_usage_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES promotions(id),
    CONSTRAINT promotion_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT promotion_usage_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE INDEX idx_promotion_usage_check ON public.promotion_usage USING btree (user_id, promotion_id);

-- Table: promotions
CREATE TABLE IF NOT EXISTS public.promotions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    code character varying(50),
    label character varying(150),
    description text,
    discount_type character varying(20) NOT NULL,
    discount_value numeric DEFAULT 0,
    min_order_amount numeric DEFAULT 0,
    min_quantity integer DEFAULT 0,
    max_discount_amount numeric,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    is_active boolean DEFAULT true,
    usage_limit_global integer,
    usage_limit_per_user integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_public boolean DEFAULT false,
    is_featured boolean DEFAULT false,
    CONSTRAINT promotions_discount_type_check CHECK (((discount_type)::text = ANY ((ARRAY['percentage'::character varying, 'fixed_amount'::character varying, 'free_delivery'::character varying])::text[]))),
    CONSTRAINT promotions_id_not_null NOT NULL id,
    CONSTRAINT promotions_discount_type_not_null NOT NULL discount_type,
    CONSTRAINT promotions_pkey PRIMARY KEY (id),
    CONSTRAINT promotions_code_key UNIQUE (code)
);

CREATE INDEX idx_promotions_code ON public.promotions USING btree (code);

-- Table: return_items
CREATE TABLE IF NOT EXISTS public.return_items (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    return_id uuid,
    medicine_id uuid,
    quantity integer NOT NULL,
    condition character varying(50) DEFAULT 'good'::character varying,
    CONSTRAINT return_items_id_not_null NOT NULL id,
    CONSTRAINT return_items_medicine_id_fkey FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    CONSTRAINT return_items_pkey PRIMARY KEY (id),
    CONSTRAINT return_items_quantity_not_null NOT NULL quantity,
    CONSTRAINT return_items_return_id_fkey FOREIGN KEY (return_id) REFERENCES returns(id) ON DELETE CASCADE
);


-- Table: returns
CREATE TABLE IF NOT EXISTS public.returns (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid,
    user_id uuid,
    status character varying(50) DEFAULT 'pending'::character varying,
    refund_amount numeric,
    reason text,
    admin_notes text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    shift_id uuid,
    processed_by uuid,
    CONSTRAINT returns_id_not_null NOT NULL id,
    CONSTRAINT returns_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT returns_pkey PRIMARY KEY (id),
    CONSTRAINT returns_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES users(id),
    CONSTRAINT returns_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES shifts(id),
    CONSTRAINT returns_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_returns_shift ON public.returns USING btree (shift_id);
CREATE INDEX idx_returns_created_at ON public.returns USING btree (created_at DESC);

-- Table: roles
CREATE TABLE IF NOT EXISTS public.roles (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(50) NOT NULL,
    description text,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT roles_id_not_null NOT NULL id,
    CONSTRAINT roles_name_key UNIQUE (name),
    CONSTRAINT roles_name_not_null NOT NULL name,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);


-- Table: shifts
CREATE TABLE IF NOT EXISTS public.shifts (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    opened_by uuid NOT NULL,
    closed_by uuid,
    opened_at timestamp without time zone NOT NULL DEFAULT now(),
    closed_at timestamp without time zone,
    total_orders integer DEFAULT 0,
    total_prescriptions integer DEFAULT 0,
    total_returns integer DEFAULT 0,
    gross_revenue numeric DEFAULT 0.00,
    net_revenue numeric DEFAULT 0.00,
    status character varying(20) DEFAULT 'open'::character varying,
    CONSTRAINT shifts_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES users(id),
    CONSTRAINT shifts_id_not_null NOT NULL id,
    CONSTRAINT shifts_opened_at_not_null NOT NULL opened_at,
    CONSTRAINT shifts_opened_by_fkey FOREIGN KEY (opened_by) REFERENCES users(id),
    CONSTRAINT shifts_opened_by_not_null NOT NULL opened_by,
    CONSTRAINT shifts_pkey PRIMARY KEY (id),
    CONSTRAINT shifts_status_check CHECK (((status)::text = ANY ((ARRAY['open'::character varying, 'closed'::character varying])::text[])))
);

CREATE INDEX idx_shifts_status ON public.shifts USING btree (status);
CREATE INDEX idx_shifts_opened_by ON public.shifts USING btree (opened_by);

-- Table: user_notifications
CREATE TABLE IF NOT EXISTS public.user_notifications (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    notification_id uuid,
    read boolean DEFAULT false,
    sent_at timestamp without time zone,
    CONSTRAINT user_notifications_id_not_null NOT NULL id,
    CONSTRAINT user_notifications_pkey PRIMARY KEY (id),
    CONSTRAINT user_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT user_notifications_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES notifications(id)
);

CREATE INDEX idx_fk_user_notif_user ON public.user_notifications USING btree (user_id);

-- Table: user_phones
CREATE TABLE IF NOT EXISTS public.user_phones (
    id integer NOT NULL DEFAULT nextval('user_phones_id_seq'::regclass),
    user_id uuid,
    phone_number character varying(20) NOT NULL,
    label character varying(50) DEFAULT 'Mobile'::character varying,
    is_default boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT user_phones_id_not_null NOT NULL id,
    CONSTRAINT user_phones_phone_number_not_null NOT NULL phone_number,
    CONSTRAINT user_phones_pkey PRIMARY KEY (id),
    CONSTRAINT user_phones_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


-- Table: user_roles
CREATE TABLE IF NOT EXISTS public.user_roles (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    assigned_at timestamp without time zone DEFAULT now(),
    CONSTRAINT user_roles_id_not_null NOT NULL id,
    CONSTRAINT user_roles_pkey PRIMARY KEY (id),
    CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_id_not_null NOT NULL role_id,
    CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT user_roles_user_id_not_null NOT NULL user_id,
    CONSTRAINT user_roles_user_id_role_id_key UNIQUE (user_id, role_id)
);

CREATE INDEX idx_user_roles_user ON public.user_roles USING btree (user_id);
CREATE INDEX idx_user_roles_role ON public.user_roles USING btree (role_id);

-- Table: users
CREATE TABLE IF NOT EXISTS public.users (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    full_name character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    password_hash text NOT NULL,
    phone character varying(20),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    avatar text,
    role character varying DEFAULT 'patient'::character varying,
    total_orders_placed integer DEFAULT 0,
    email_verified boolean DEFAULT false,
    CONSTRAINT users_id_not_null NOT NULL id,
    CONSTRAINT users_full_name_not_null NOT NULL full_name,
    CONSTRAINT users_email_not_null NOT NULL email,
    CONSTRAINT users_password_hash_not_null NOT NULL password_hash,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE INDEX idx_users_phone ON public.users USING btree (phone);
CREATE INDEX idx_users_name_trgm ON public.users USING gin (full_name gin_trgm_ops);
CREATE INDEX idx_users_email_trgm ON public.users USING gin (email gin_trgm_ops);

